### PR TITLE
Prevent error with invalid chars in multigroup components

### PR DESCRIPTION
**Pull request by MCrafterzz**
It would be even neater to remove them from the stringproperty automatically but I can't find a way to do that.

### CODE REVIEW

**Comment by MCrafterzz** [comment]
@ranjian0 fixed

**Comment by ranjian0** [comment]
> It would be even neater to remove them from the stringproperty automatically but I can't find a way to do that.

This would be a much cleaner solution.

**Comment by MCrafterzz** [comment]
> It would be even neater to remove them from the stringproperty automatically but I can't find a way to do that.
> 
> This would be a much cleaner solution.

Any idea how that would work? Setting float properties etc you could just do = 5 for example but you can't do = "example" for the string property and I can't find anything on the internet either. I feel like I somehow need to convert the string to whatever the Stringproperty uses.

**Comment by ranjian0** [comment]
> > It would be even neater to remove them from the stringproperty automatically but I can't find a way to do that.
> > This would be a much cleaner solution.
> 
> Any idea how that would work? Setting float properties etc you could just do = 5 for example but you can't do = "example" for the string property and I can't find anything on the internet either. I feel like I somehow need to convert the string to whatever the Stringproperty uses.

I just did a small test in blender console and it seems to work

```python
>>> bpy.types.Object.my_str = bpy.props.StringProperty()
>>> C.object
bpy.data.objects['building_001']

>>> C.object.my_str
''

>>> C.object.my_str = "hello"
>>> C.object.my_str
'hello'

>>> 
```

**Pull request merged**
