### PR TITLE
Feature/double door

### PR DESCRIPTION
**Pull request by luckykadam**
changes:
1. Double door feature as tick box in UI
Screenshot 2020-03-17 at 2 57 01 PM
Screenshot 2020-03-17 at 2 57 07 PM

### CODE REVIEW

**Comment by luckykadam** [comment]
@ranjian0 I encountered the same problem of n-gons here as well.

Screenshot 2020-03-17 at 2 58 27 PM

I suggest that for operation which can leave adjacent geometry inconsistent(n-gons), we can isolate the operating face before applying operation.

Simplest way of isolating is inseting with very small thickness.
```
bmesh.ops.inset_individual(bm, faces=[face], thickness=0.0001)
```

Advantages of this approach:
1. Consistent across all the operators.
2. Similar approach can be used to support operators to rectangular n-gons, by inseting(variation of) to get a rectangular face.

**Comment by ranjian0** [comment]
This looks fine, but there is nothing that makes it clear that this is a double door. In particular, I think we should have a small extrusion/bar across the middle just to emphasize the distinction.

Imgur  Imgur

Maybe this could be optional too.
I would love to get a feel for how it would look with this addition.

The inset trick for ngons is a good approach.

**Comment by luckykadam** [comment]
@ranjian0 thanks for the review.

Actually for other fill types this distinction is clear.

Screenshot 2020-03-17 at 6 09 27 PM

In real life the double door does not have a bar between them.

The use case you mentioned is also useful. But, I feel these should be considered two different door, somehow combined under same arch. If would be great to include windows also in this combination. I will think about this problem as well. But, I believe this should be a task in its own.

**Comment by ranjian0** [comment]
I guess the glass pane fill is the problem. The panel fill looks great, with a clear distinction of both sides of the door. Louver fill should also look good.

You are right, double doors should not have a bar in the middle. We could provide it as an option that is off by default.

**Comment by luckykadam** [comment]
2 doors with a bar, is as important as a door and a window with a bar.

Proposal:
It would be great to have a new feature where we can combine doors and windows with shared arch. This can be very flexible: triple door (just like in offices main entrance), door with a window, etc.

examples:

a4c33dfb967cb044c8377b7983dd089f


I will start working on this feature and share my ideas.

**Comment by ranjian0** [comment]
That is an interesting feature. You should create a new issue for it with the `enhancement` label.

**Pull request merged**
