### PR TITLE
Fix stairs railing

### LINKED ISSUE #67: Stair Railing Issue Tracker
1. [ ] Wierd geometry when step count is set to one. See below.

Imgur

2. [ ] Playing with step height causes the following behaviour:

Imgur

3. [ ] Creating new stairs sometimes results in a weird offset

Imgur

4. [ ] Increasing step width distorts the corner post location on the landing 

Imgur

### PR DESCRIPTION
**Pull request by luckykadam**
1. fix stairs in opposite direction issue
2. fix railings density when step count = 1
3. fix criss-cross railings
4. fix landing corner post distortion

fixes #67

### CODE REVIEW

**Comment by ranjian0** [comment]
reviewing!

**Comment by ranjian0** [comment]
> 4. fix landing corner post distortion

Doesn't seem to be fixed, increasing step width still causes the farmost corner posts to move backwards.

**Comment by luckykadam** [comment]
> > 1. fix landing corner post distortion
> 
> Doesn't seem to be fixed, increasing step width still causes the farmost corner posts to move backwards.

Thats the only fix. We need to have front corner post coherent with stair post. Moving front cornet post will make the slope angle of railing different from stairs angle.

**Comment by ranjian0** [comment]
> Thats the only fix. We need to have front corner post coherent with stair post. Moving front cornet post will make the slope angle of railing different from stairs angle.

How do you mean? landing width and step width are independent. Without landing, the corner posts behave correctly, but with landing, the posts should not move.

**Comment by ranjian0** [comment]
Also, have been thinking about railing, esp **Post fill type** and after a bit of research, it seems posts should not be touching down. 

Here are examples:
Imgur

Imgur
Imgur
Imgur

This will hopefully solve issues with filling posts for stairs and will make density option work more consistently.

What do you think??

**Comment by luckykadam** [comment]
> How do you mean? landing width and step width are independent. Without landing, the corner posts behave correctly, but with landing, the posts should not move.

I want to maintain the angle of railing same as stair angle. To achieve this I want the corner post at `step_width/2` distance from edge. Which is what happens when there is no landing (center of step is `step_width/2` away from edge.

**Comment by luckykadam** [comment]
> What do you think??

This can be another fill type, where density would not be an issue.

**Comment by ranjian0** [comment]
> > How do you mean? landing width and step width are independent. Without landing, the corner posts behave correctly, but with landing, the posts should not move.
> 
> I want to maintain the angle of railing same as stair angle. To achieve this I want the corner post at `step_width/2` distance from edge. Which is what happens when there is no landing (center of step is `step_width/2` away from edge.

This behaviour is extremely unintuitive with landing.

**Comment by ranjian0** [comment]
> > What do you think??
> 
> This can be another fill type, where density would not be an issue.

Having two post fill types doesn't make sense?? Try googling for stairs with post fill. All images have the behaviour that I have mentioned, not the one that is currently implemented.

**Pull request merged**
